"""The generic-agentsmd adapter (§7.4): AGENTS.md for non-Claude runtimes."""

import pytest
from conftest import run_cli, write_module

SKILL = {"demo-skill": {"SKILL.md": "---\nname: demo-skill\ndescription: x\n---\n"}}
AGENT = {
    "demo-agent": {
        "name": "demo-agent",
        "module": "demo",
        "description": "Tends the demo domain.",
        "mission": "Tend {{root}}.",
        "scope": {"read": ["{{root}}/**"], "write": ["{{root}}/Out/**"]},
        "escalate_when": ["anything odd happens in {{root}}"],
        "disclaimer": "Not advice.",
        "triggers": ["log this thing"],
    }
}


@pytest.fixture
def home(tmp_path, monkeypatch):
    modules_root = tmp_path / "modules"
    write_module(modules_root, "core")
    write_module(
        modules_root,
        "demo",
        variables=[{"key": "root", "prompt": "Root", "default": "Demo-Stuff"}],
        folders=["{{root}}/Out"],
        skills=SKILL,
        agents=AGENT,
    )
    monkeypatch.setenv("ONYXIAN_HOME", str(tmp_path))
    return tmp_path


def init_with_runtimes(home, runtimes: str):
    answers = home / "a.yaml"
    answers.write_text(
        f"framework: {{ runtimes: [{runtimes}] }}\nmodules: {{ demo: {{}} }}\n", encoding="utf-8"
    )
    vault = home / f"vault-{runtimes.replace(', ', '-')}"
    assert run_cli("init", str(vault), "--answers", str(answers), "--yes") == 0
    return vault


def test_generic_runtime_gets_agents_md_with_the_full_surface(home):
    vault = init_with_runtimes(home, "generic")
    text = (vault / "AGENTS.md").read_text(encoding="utf-8")
    assert "generated by Onyxian" in text
    assert "- **demo** 0.1.0" in text
    assert "`.claude/skills/demo-skill/SKILL.md`" in text
    assert "# Agent: demo-agent" in text
    assert "Tend Demo-Stuff." in text  # mission rendered over resolved variables
    assert "- `Demo-Stuff/Out/**`" in text
    assert "anything odd happens in Demo-Stuff" in text
    assert "Not advice." in text
    assert "delete, move, rename, or restructure" in text  # the standing floor
    # No Claude-only artifacts for a generic-only vault.
    assert not (vault / ".claude" / "agents").exists()


def test_claude_only_vault_has_no_agents_md(home):
    vault = init_with_runtimes(home, "claude-code")
    assert not (vault / "AGENTS.md").exists()
    assert (vault / ".claude" / "agents" / "demo-agent.md").is_file()


def test_dual_runtime_vault_gets_both_surfaces(home, capsys):
    vault = init_with_runtimes(home, "claude-code, codex")
    assert (vault / "AGENTS.md").is_file()
    assert (vault / ".claude" / "agents" / "demo-agent.md").is_file()
    # AGENTS.md is managed like everything else: converged and doctor-clean.
    capsys.readouterr()
    assert run_cli("doctor", "--vault", str(vault)) == 0
    out = capsys.readouterr().out
    assert "home-directory skill installs" in out  # honest note about what is not automated yet


def test_claude_code_runtime_gets_claude_md_and_digest(home):
    vault = init_with_runtimes(home, "claude-code")
    claude_md = (vault / "CLAUDE.md").read_text(encoding="utf-8")
    assert "@.claude/onyxian.md" in claude_md  # the seeded wrapper imports the managed digest
    digest = (vault / ".claude" / "onyxian.md").read_text(encoding="utf-8")
    assert "`obsidian`" in digest and "vault-operations" in digest  # the operating contract
    assert (
        "- **demo-agent** — Tends the demo domain." in digest
    )  # routing table, description resolved
    assert "log this thing" in digest  # the first trigger surfaces in the routing digest
    assert not (vault / "AGENTS.md").exists()  # claude-only: no AGENTS.md


def test_generic_only_vault_has_no_claude_orientation(home):
    vault = init_with_runtimes(home, "generic")
    assert not (vault / "CLAUDE.md").exists()
    assert not (vault / ".claude" / "onyxian.md").exists()


def test_claude_md_is_seeded_and_left_to_the_user(home):
    vault = init_with_runtimes(home, "claude-code")
    (vault / "CLAUDE.md").write_text("my own notes\n", encoding="utf-8")  # user takes it over
    assert run_cli("apply", "--vault", str(vault), "--yes") == 0
    assert (vault / "CLAUDE.md").read_text(
        encoding="utf-8"
    ) == "my own notes\n"  # seeded: never rewritten
